# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountInfoWidgetBase.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AccountInfoWidgetBase(object):
    def setupUi(self, AccountInfoWidgetBase):
        AccountInfoWidgetBase.setObjectName(_fromUtf8("AccountInfoWidgetBase"))
        AccountInfoWidgetBase.resize(382, 584)
        self.verticalLayout_5 = QtGui.QVBoxLayout(AccountInfoWidgetBase)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(AccountInfoWidgetBase)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mainInfoTab = QtGui.QWidget()
        self.mainInfoTab.setObjectName(_fromUtf8("mainInfoTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.mainInfoTab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_4 = QtGui.QGroupBox(self.mainInfoTab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.accountIdLabel = QtGui.QLabel(self.groupBox_4)
        self.accountIdLabel.setObjectName(_fromUtf8("accountIdLabel"))
        self.gridLayout.addWidget(self.accountIdLabel, 0, 0, 1, 1)
        self.accountIdLineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.accountIdLineEdit.setObjectName(_fromUtf8("accountIdLineEdit"))
        self.gridLayout.addWidget(self.accountIdLineEdit, 0, 1, 1, 1)
        self.userNameLabel = QtGui.QLabel(self.groupBox_4)
        self.userNameLabel.setObjectName(_fromUtf8("userNameLabel"))
        self.gridLayout.addWidget(self.userNameLabel, 1, 0, 1, 1)
        self.userNameLineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.userNameLineEdit.setObjectName(_fromUtf8("userNameLineEdit"))
        self.gridLayout.addWidget(self.userNameLineEdit, 1, 1, 1, 1)
        self.passwordLabel = QtGui.QLabel(self.groupBox_4)
        self.passwordLabel.setObjectName(_fromUtf8("passwordLabel"))
        self.gridLayout.addWidget(self.passwordLabel, 2, 0, 1, 1)
        self.passwordLineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.passwordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordLineEdit.setObjectName(_fromUtf8("passwordLineEdit"))
        self.gridLayout.addWidget(self.passwordLineEdit, 2, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.mainInfoTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.balanceTableView = QtGui.QTableView(self.groupBox_3)
        self.balanceTableView.setObjectName(_fromUtf8("balanceTableView"))
        self.balanceTableView.verticalHeader().setDefaultSectionSize(16)
        self.balanceTableView.verticalHeader().setMinimumSectionSize(16)
        self.verticalLayout.addWidget(self.balanceTableView)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.balanceDateEdit = QtGui.QDateEdit(self.groupBox_3)
        self.balanceDateEdit.setObjectName(_fromUtf8("balanceDateEdit"))
        self.horizontalLayout_2.addWidget(self.balanceDateEdit)
        self.balanceAmountLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.balanceAmountLineEdit.setObjectName(_fromUtf8("balanceAmountLineEdit"))
        self.horizontalLayout_2.addWidget(self.balanceAmountLineEdit)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.balanceAddButton = QtGui.QPushButton(self.groupBox_3)
        self.balanceAddButton.setObjectName(_fromUtf8("balanceAddButton"))
        self.horizontalLayout_2.addWidget(self.balanceAddButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.tabWidget.addTab(self.mainInfoTab, _fromUtf8(""))
        self.ofxInfoTab = QtGui.QWidget()
        self.ofxInfoTab.setObjectName(_fromUtf8("ofxInfoTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.ofxInfoTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.ofxInfoTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.oFXFidLabel = QtGui.QLabel(self.groupBox)
        self.oFXFidLabel.setObjectName(_fromUtf8("oFXFidLabel"))
        self.gridLayout_2.addWidget(self.oFXFidLabel, 0, 0, 1, 1)
        self.oFXURLLineEdit = QtGui.QLineEdit(self.groupBox)
        self.oFXURLLineEdit.setObjectName(_fromUtf8("oFXURLLineEdit"))
        self.gridLayout_2.addWidget(self.oFXURLLineEdit, 3, 1, 1, 1)
        self.oFXURLLabel = QtGui.QLabel(self.groupBox)
        self.oFXURLLabel.setObjectName(_fromUtf8("oFXURLLabel"))
        self.gridLayout_2.addWidget(self.oFXURLLabel, 3, 0, 1, 1)
        self.oFXBankIDLineEdit = QtGui.QLineEdit(self.groupBox)
        self.oFXBankIDLineEdit.setObjectName(_fromUtf8("oFXBankIDLineEdit"))
        self.gridLayout_2.addWidget(self.oFXBankIDLineEdit, 2, 1, 1, 1)
        self.oFXBankIDLabel = QtGui.QLabel(self.groupBox)
        self.oFXBankIDLabel.setObjectName(_fromUtf8("oFXBankIDLabel"))
        self.gridLayout_2.addWidget(self.oFXBankIDLabel, 2, 0, 1, 1)
        self.oFXFiorgLabel = QtGui.QLabel(self.groupBox)
        self.oFXFiorgLabel.setObjectName(_fromUtf8("oFXFiorgLabel"))
        self.gridLayout_2.addWidget(self.oFXFiorgLabel, 1, 0, 1, 1)
        self.oFXFiorgLineEdit = QtGui.QLineEdit(self.groupBox)
        self.oFXFiorgLineEdit.setObjectName(_fromUtf8("oFXFiorgLineEdit"))
        self.gridLayout_2.addWidget(self.oFXFiorgLineEdit, 1, 1, 1, 1)
        self.oFXFidLineEdit = QtGui.QLineEdit(self.groupBox)
        self.oFXFidLineEdit.setObjectName(_fromUtf8("oFXFidLineEdit"))
        self.gridLayout_2.addWidget(self.oFXFidLineEdit, 0, 1, 1, 1)
        self.oFXAccountTypeComboBox = QtGui.QComboBox(self.groupBox)
        self.oFXAccountTypeComboBox.setObjectName(_fromUtf8("oFXAccountTypeComboBox"))
        self.oFXAccountTypeComboBox.addItem(_fromUtf8(""))
        self.oFXAccountTypeComboBox.addItem(_fromUtf8(""))
        self.oFXAccountTypeComboBox.addItem(_fromUtf8(""))
        self.oFXAccountTypeComboBox.addItem(_fromUtf8(""))
        self.oFXAccountTypeComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.oFXAccountTypeComboBox, 4, 1, 1, 1)
        self.oFXAccountTypeLabel = QtGui.QLabel(self.groupBox)
        self.oFXAccountTypeLabel.setObjectName(_fromUtf8("oFXAccountTypeLabel"))
        self.gridLayout_2.addWidget(self.oFXAccountTypeLabel, 4, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.ofxInfoTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.scraperClassLabel = QtGui.QLabel(self.groupBox_2)
        self.scraperClassLabel.setObjectName(_fromUtf8("scraperClassLabel"))
        self.gridLayout_3.addWidget(self.scraperClassLabel, 0, 0, 1, 1)
        self.scraperClassLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.scraperClassLineEdit.setObjectName(_fromUtf8("scraperClassLineEdit"))
        self.gridLayout_3.addWidget(self.scraperClassLineEdit, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 198, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.ofxInfoTab, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.importButton = QtGui.QPushButton(AccountInfoWidgetBase)
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.horizontalLayout.addWidget(self.importButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.discardButton = QtGui.QPushButton(AccountInfoWidgetBase)
        self.discardButton.setObjectName(_fromUtf8("discardButton"))
        self.horizontalLayout.addWidget(self.discardButton)
        self.saveButton = QtGui.QPushButton(AccountInfoWidgetBase)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(AccountInfoWidgetBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AccountInfoWidgetBase)

    def retranslateUi(self, AccountInfoWidgetBase):
        AccountInfoWidgetBase.setWindowTitle(_translate("AccountInfoWidgetBase", "Form", None))
        self.groupBox_4.setTitle(_translate("AccountInfoWidgetBase", "Basic Information", None))
        self.accountIdLabel.setText(_translate("AccountInfoWidgetBase", "Account ID", None))
        self.userNameLabel.setText(_translate("AccountInfoWidgetBase", "User Name", None))
        self.passwordLabel.setText(_translate("AccountInfoWidgetBase", "Password", None))
        self.groupBox_3.setTitle(_translate("AccountInfoWidgetBase", "Known Account Balances", None))
        self.label_5.setText(_translate("AccountInfoWidgetBase", "$", None))
        self.balanceAddButton.setText(_translate("AccountInfoWidgetBase", "Add", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainInfoTab), _translate("AccountInfoWidgetBase", "Basic", None))
        self.groupBox.setTitle(_translate("AccountInfoWidgetBase", "OFX Information", None))
        self.label_3.setText(_translate("AccountInfoWidgetBase", "<html><head/><body><p>Import data from your financial institution using the <a href=\"http://www.ofxhome.com\"><span style=\" text-decoration: underline; color:#0000ff;\">OFX protocol</span></a><br/></p></body></html>", None))
        self.oFXFidLabel.setText(_translate("AccountInfoWidgetBase", "OFX fid", None))
        self.oFXURLLabel.setText(_translate("AccountInfoWidgetBase", "OFX URL", None))
        self.oFXBankIDLabel.setText(_translate("AccountInfoWidgetBase", "OFX Bank ID", None))
        self.oFXFiorgLabel.setText(_translate("AccountInfoWidgetBase", "OFX fiorg", None))
        self.oFXAccountTypeComboBox.setItemText(0, _translate("AccountInfoWidgetBase", "Credit Card", None))
        self.oFXAccountTypeComboBox.setItemText(1, _translate("AccountInfoWidgetBase", "Checking", None))
        self.oFXAccountTypeComboBox.setItemText(2, _translate("AccountInfoWidgetBase", "Savings", None))
        self.oFXAccountTypeComboBox.setItemText(3, _translate("AccountInfoWidgetBase", "Money Market", None))
        self.oFXAccountTypeComboBox.setItemText(4, _translate("AccountInfoWidgetBase", "Credit Line", None))
        self.oFXAccountTypeLabel.setText(_translate("AccountInfoWidgetBase", "OFX Account Type", None))
        self.groupBox_2.setTitle(_translate("AccountInfoWidgetBase", "Web Scraping", None))
        self.label_4.setText(_translate("AccountInfoWidgetBase", "Import data from your financial institution\'s web page. <br>", None))
        self.scraperClassLabel.setText(_translate("AccountInfoWidgetBase", "Web-page", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ofxInfoTab), _translate("AccountInfoWidgetBase", "Importing", None))
        self.importButton.setText(_translate("AccountInfoWidgetBase", "Import", None))
        self.discardButton.setText(_translate("AccountInfoWidgetBase", "Discard", None))
        self.saveButton.setText(_translate("AccountInfoWidgetBase", "Save", None))

