# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SavFin(object):
    def setupUi(self, SavFin):
        SavFin.setObjectName(_fromUtf8("SavFin"))
        SavFin.resize(813, 640)
        self.centralwidget = QtGui.QWidget(SavFin)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.timeExtentsLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeExtentsLabel.sizePolicy().hasHeightForWidth())
        self.timeExtentsLabel.setSizePolicy(sizePolicy)
        self.timeExtentsLabel.setText(_fromUtf8(""))
        self.timeExtentsLabel.setTextFormat(QtCore.Qt.RichText)
        self.timeExtentsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.timeExtentsLabel.setObjectName(_fromUtf8("timeExtentsLabel"))
        self.horizontalLayout.addWidget(self.timeExtentsLabel)
        self.prevIntervalButton = QtGui.QPushButton(self.centralwidget)
        self.prevIntervalButton.setObjectName(_fromUtf8("prevIntervalButton"))
        self.horizontalLayout.addWidget(self.prevIntervalButton)
        self.durationCombo = QtGui.QComboBox(self.centralwidget)
        self.durationCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.durationCombo.setObjectName(_fromUtf8("durationCombo"))
        self.durationCombo.addItem(_fromUtf8(""))
        self.durationCombo.addItem(_fromUtf8(""))
        self.durationCombo.addItem(_fromUtf8(""))
        self.durationCombo.addItem(_fromUtf8(""))
        self.durationCombo.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.durationCombo)
        self.nextIntervalButton = QtGui.QPushButton(self.centralwidget)
        self.nextIntervalButton.setObjectName(_fromUtf8("nextIntervalButton"))
        self.horizontalLayout.addWidget(self.nextIntervalButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.expenseReportTab = ExpenseReport()
        self.expenseReportTab.setObjectName(_fromUtf8("expenseReportTab"))
        self.tabWidget.addTab(self.expenseReportTab, _fromUtf8(""))
        self.assetViewTab = AssetView()
        self.assetViewTab.setObjectName(_fromUtf8("assetViewTab"))
        self.tabWidget.addTab(self.assetViewTab, _fromUtf8(""))
        self.selectedTransactionsTab = SelectedTransactionTableView()
        self.selectedTransactionsTab.setObjectName(_fromUtf8("selectedTransactionsTab"))
        self.tabWidget.addTab(self.selectedTransactionsTab, _fromUtf8(""))
        self.transactionsTab = FilteredTransactionView()
        self.transactionsTab.setObjectName(_fromUtf8("transactionsTab"))
        self.tabWidget.addTab(self.transactionsTab, _fromUtf8(""))
        self.accountsTab = QtGui.QWidget()
        self.accountsTab.setObjectName(_fromUtf8("accountsTab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.accountsTab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.accountTreeView = AccountTreeView(self.accountsTab)
        self.accountTreeView.setObjectName(_fromUtf8("accountTreeView"))
        self.horizontalLayout_2.addWidget(self.accountTreeView)
        self.accountInfoWidget = AccountInfoWidget(self.accountsTab)
        self.accountInfoWidget.setObjectName(_fromUtf8("accountInfoWidget"))
        self.horizontalLayout_2.addWidget(self.accountInfoWidget)
        self.tabWidget.addTab(self.accountsTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        SavFin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SavFin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Import = QtGui.QMenu(self.menubar)
        self.menu_Import.setObjectName(_fromUtf8("menu_Import"))
        self.menu_Rules = QtGui.QMenu(self.menubar)
        self.menu_Rules.setObjectName(_fromUtf8("menu_Rules"))
        self.menu_Transactions = QtGui.QMenu(self.menubar)
        self.menu_Transactions.setObjectName(_fromUtf8("menu_Transactions"))
        SavFin.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(SavFin)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionQuit = QtGui.QAction(SavFin)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionImportBofaStatement = QtGui.QAction(SavFin)
        self.actionImportBofaStatement.setObjectName(_fromUtf8("actionImportBofaStatement"))
        self.actionImportChaseStatement = QtGui.QAction(SavFin)
        self.actionImportChaseStatement.setObjectName(_fromUtf8("actionImportChaseStatement"))
        self.actionSave = QtGui.QAction(SavFin)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSaveAs = QtGui.QAction(SavFin)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionImportDCUStatement = QtGui.QAction(SavFin)
        self.actionImportDCUStatement.setObjectName(_fromUtf8("actionImportDCUStatement"))
        self.actionImportStatement = QtGui.QAction(SavFin)
        self.actionImportStatement.setObjectName(_fromUtf8("actionImportStatement"))
        self.actionSetDurationMonth = QtGui.QAction(SavFin)
        self.actionSetDurationMonth.setObjectName(_fromUtf8("actionSetDurationMonth"))
        self.actionSetDurationYear = QtGui.QAction(SavFin)
        self.actionSetDurationYear.setObjectName(_fromUtf8("actionSetDurationYear"))
        self.actionSetDurationAll = QtGui.QAction(SavFin)
        self.actionSetDurationAll.setObjectName(_fromUtf8("actionSetDurationAll"))
        self.actionAddRule = QtGui.QAction(SavFin)
        self.actionAddRule.setObjectName(_fromUtf8("actionAddRule"))
        self.actionManageRules = QtGui.QAction(SavFin)
        self.actionManageRules.setObjectName(_fromUtf8("actionManageRules"))
        self.action_All_accounts = QtGui.QAction(SavFin)
        self.action_All_accounts.setObjectName(_fromUtf8("action_All_accounts"))
        self.actionDownloadAccounts = QtGui.QAction(SavFin)
        self.actionDownloadAccounts.setObjectName(_fromUtf8("actionDownloadAccounts"))
        self.actionSetMasterPassword = QtGui.QAction(SavFin)
        self.actionSetMasterPassword.setObjectName(_fromUtf8("actionSetMasterPassword"))
        self.actionImportOfxStatement = QtGui.QAction(SavFin)
        self.actionImportOfxStatement.setObjectName(_fromUtf8("actionImportOfxStatement"))
        self.actionDetectDuplicates = QtGui.QAction(SavFin)
        self.actionDetectDuplicates.setCheckable(True)
        self.actionDetectDuplicates.setObjectName(_fromUtf8("actionDetectDuplicates"))
        self.actionImportAmazonVISAStatement = QtGui.QAction(SavFin)
        self.actionImportAmazonVISAStatement.setObjectName(_fromUtf8("actionImportAmazonVISAStatement"))
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSaveAs)
        self.menu_File.addAction(self.actionSetMasterPassword)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menu_Import.addAction(self.actionImportStatement)
        self.menu_Rules.addAction(self.actionAddRule)
        self.menu_Rules.addAction(self.actionManageRules)
        self.menu_Transactions.addAction(self.actionDetectDuplicates)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Import.menuAction())
        self.menubar.addAction(self.menu_Rules.menuAction())
        self.menubar.addAction(self.menu_Transactions.menuAction())

        self.retranslateUi(SavFin)
        self.durationCombo.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.accountTreeView, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), self.accountInfoWidget.selectAccount)
        QtCore.QMetaObject.connectSlotsByName(SavFin)

    def retranslateUi(self, SavFin):
        SavFin.setWindowTitle(_translate("SavFin", "Savfin", None))
        self.prevIntervalButton.setText(_translate("SavFin", "<<", None))
        self.durationCombo.setItemText(0, _translate("SavFin", "Yearly", None))
        self.durationCombo.setItemText(1, _translate("SavFin", "Year To Date", None))
        self.durationCombo.setItemText(2, _translate("SavFin", "Monthly", None))
        self.durationCombo.setItemText(3, _translate("SavFin", "Past Year", None))
        self.durationCombo.setItemText(4, _translate("SavFin", "All", None))
        self.nextIntervalButton.setText(_translate("SavFin", ">>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.expenseReportTab), _translate("SavFin", "Expense Report", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.assetViewTab), _translate("SavFin", "Asset View", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectedTransactionsTab), _translate("SavFin", "Selected Transitions", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.transactionsTab), _translate("SavFin", "All Transactions", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.accountsTab), _translate("SavFin", "Accounts", None))
        self.menu_File.setTitle(_translate("SavFin", "&File", None))
        self.menu_Import.setTitle(_translate("SavFin", "&Import", None))
        self.menu_Rules.setTitle(_translate("SavFin", "&Rules", None))
        self.menu_Transactions.setTitle(_translate("SavFin", "&Transactions", None))
        self.actionOpen.setText(_translate("SavFin", "&Open...", None))
        self.actionOpen.setShortcut(_translate("SavFin", "Ctrl+O", None))
        self.actionQuit.setText(_translate("SavFin", "&Quit", None))
        self.actionImportBofaStatement.setText(_translate("SavFin", "Bank of &America Statement", None))
        self.actionImportChaseStatement.setText(_translate("SavFin", "Chase &Visa Statement", None))
        self.actionSave.setText(_translate("SavFin", "&Save", None))
        self.actionSave.setShortcut(_translate("SavFin", "Ctrl+S", None))
        self.actionSaveAs.setText(_translate("SavFin", "Save &As...", None))
        self.actionImportDCUStatement.setText(_translate("SavFin", "D&CU Statement", None))
        self.actionImportStatement.setText(_translate("SavFin", "&Pdf/Ofx statement", None))
        self.actionSetDurationMonth.setText(_translate("SavFin", "&Month", None))
        self.actionSetDurationYear.setText(_translate("SavFin", "&Year", None))
        self.actionSetDurationAll.setText(_translate("SavFin", "&All", None))
        self.actionAddRule.setText(_translate("SavFin", "&Add Rule...", None))
        self.actionManageRules.setText(_translate("SavFin", "&Manage Rules...", None))
        self.action_All_accounts.setText(_translate("SavFin", "&All accounts", None))
        self.actionDownloadAccounts.setText(_translate("SavFin", "&Download all accounts", None))
        self.actionSetMasterPassword.setText(_translate("SavFin", "Set Master Password...", None))
        self.actionImportOfxStatement.setText(_translate("SavFin", "Import OF&X statement", None))
        self.actionDetectDuplicates.setText(_translate("SavFin", "&Detect Duplicates", None))
        self.actionImportAmazonVISAStatement.setText(_translate("SavFin", "Amazon VISA Statement", None))

from AccountInfoWidget import AccountInfoWidget
from AccountTreeView import AccountTreeView
from AssetView import AssetView
from ExpenseReport import ExpenseReport
from FilteredTransactionView import FilteredTransactionView
from SelectedTransactionTableView import SelectedTransactionTableView
